// Nameing: PAGE_ACTION_STATUS

export const ADMINSTOREFORM_EDITFORM_CHANGE = 'ADMINSTOREFORM_EDITFORM_CHANGE'

export const STOREOWNERSTOREFORM_EDITFORM_CHANGE = 'STOREOWNERSTOREFORM_EDITFORM_CHANGE'

export const STOREOWNERPRODUCTFORM_EDITFORM_CHANGE = 'STOREOWNERPRODUCTFORM_EDITFORM_CHANGE'
